baseURL = "https://all-knowing-dns.zekjur.net/"
languageCode = "en-us"
title = "AllKnowingDNS — Tiny DNS server for IPv6 Reverse DNS"
theme = "all-knowing-dns"
disableKinds = ["RSS", "taxonomyTerm"]
publishDir = "docs"

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
